# Generated by scripts/scout_formula.py (glider monorepo) for scout 3.4.0;
# regenerated on every scout release — do not edit by hand.
class Scout < Formula
  desc "Universal read-only code-intelligence MCP server"
  homepage "https://glidermcp.com"
  version "3.4.0"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/glidermcp/scout/releases/download/scout-v3.4.0/scout-darwin-arm64-v3.4.0.tar.gz"
      sha256 "087e6dd14fde57fdaf6ddd2e31a1cc11d9fe1da3785fd25e7800b8f70cb868dd"
    end
    on_intel do
      url "https://github.com/glidermcp/scout/releases/download/scout-v3.4.0/scout-darwin-x64-v3.4.0.tar.gz"
      sha256 "a247a443c7aa0819b5d1b5322869155e8346e02d6660448f49683f506779fac3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/glidermcp/scout/releases/download/scout-v3.4.0/scout-linux-arm64-v3.4.0.tar.gz"
      sha256 "e5a0c005b9c7898cd914655d4265bb710418d524b60bb446dcf71d6963b9deac"
    end
    on_intel do
      url "https://github.com/glidermcp/scout/releases/download/scout-v3.4.0/scout-linux-x64-v3.4.0.tar.gz"
      sha256 "040c30414607a157d34abec50d8c16bb1235983be87e06af1e17a9f6515cdf2f"
    end
  end

  def install
    bin.install "scout"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/scout --version")
  end
end
