# Generated by scripts/scout_formula.py (glider monorepo) for scout 1.2.1;
# regenerated on every scout release — do not edit by hand.
class Scout < Formula
  desc "Universal read-only code-intelligence MCP server"
  homepage "https://glidermcp.com"
  version "1.2.1"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/glidermcp/scout/releases/download/scout-v1.2.1/scout-darwin-arm64-v1.2.1.tar.gz"
      sha256 "4e4f552274008b256f1daabafec486edd34836bc8868bf59e2a8d77d001ee6ec"
    end
    on_intel do
      url "https://github.com/glidermcp/scout/releases/download/scout-v1.2.1/scout-darwin-x64-v1.2.1.tar.gz"
      sha256 "7ee614328a0389a3467c39f4550ea4e46be4c27dd89f009607fa59046ff10210"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/glidermcp/scout/releases/download/scout-v1.2.1/scout-linux-arm64-v1.2.1.tar.gz"
      sha256 "b56494a68422d27fe9a44e48e4b455a5e495e2ca81f4c858140353834992cbaf"
    end
    on_intel do
      url "https://github.com/glidermcp/scout/releases/download/scout-v1.2.1/scout-linux-x64-v1.2.1.tar.gz"
      sha256 "70bb7165799f49fccb471731ec63dca5a4d14bbdf85efa53a159ac24935c3683"
    end
  end

  def install
    bin.install "scout"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/scout --version")
  end
end
