# Generated by scripts/scout_formula.py (glider monorepo) for scout 0.5.0;
# regenerated on every scout release — do not edit by hand.
class Scout < Formula
  desc "Universal read-only code-intelligence MCP server"
  homepage "https://glidermcp.com"
  version "0.5.0"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/glidermcp/scout/releases/download/scout-v0.5.0/scout-darwin-arm64-v0.5.0.tar.gz"
      sha256 "b8ce4c2d4e65a6bcc749f9b961959dad6172f380d464a804a07a718ec1d41e57"
    end
    on_intel do
      url "https://github.com/glidermcp/scout/releases/download/scout-v0.5.0/scout-darwin-x64-v0.5.0.tar.gz"
      sha256 "a95a3198d666d6126c304e3af2909f6df07862ece338006789899b765d8a2344"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/glidermcp/scout/releases/download/scout-v0.5.0/scout-linux-arm64-v0.5.0.tar.gz"
      sha256 "75e0451b99b48fc17a51c2509cc4f16a92e0b34f1bd20f0e3c7d7f1b800dd335"
    end
    on_intel do
      url "https://github.com/glidermcp/scout/releases/download/scout-v0.5.0/scout-linux-x64-v0.5.0.tar.gz"
      sha256 "1f217ee8e031b9b1b4e5a21e9aa937bacc6d4a9c43f4bea82ad0bd94bc942b48"
    end
  end

  def install
    bin.install "scout"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/scout --version")
  end
end
